### ISSUE TITLE
Drop Key drops wrong item

### ISSUE THREAD

**Issue by MikeGamerGuy** [No3371/TLD-QoL#2]
Pressing the Drop Key does not drop the selected item. It drops the preceding item in the row and then selects the slot of the actioned item stack. A second press of Drop Key will drop the item preceding the newly selected item, and so on.  If the selected item is at the front (left most) of the row, then Drop Key drops the last item in the row and then selects the last item stack in the row.

Ex: If the Selected Slot is Row 1, Column 2, pressing the drop key drops Row 1, Column 1 and then selects Row 1, Column 1.
If the Selected Slot is Row 1, Colum 1, pressing the drop key drops Row 1, Column 5 and then selects Row 1, Column 5.

Can anyone confirm this bug?

**Comment by No3371** [comment]
Just tested it, works correctly on my side.

**Comment by MikeGamerGuy** [comment]
Resetting my keybinds with the standard in-game option seems to have fixed it.
