### ISSUE TITLE
Can't transfert even 1 item to container if total stack is too much

### ISSUE THREAD

**Issue by Fozzy50** [No3371/TLD-QoL#3]
Hi.
I have stacked item in back pack (inventory). I want to transfer some (1) to container. There is way enough room in container for several items, but not the whole stack. I just double-click the stacked item, but the PickUnits UI don't even show (bug !); so I can't even transfer 1...
Regards.

**Comment by No3371** [comment]
What item is it? How much weight is left?

QoL basically only bridge input to existing TLD code, by clicking on the original arrow button it seems like that's how it has been working, not a new issue created by QoL:

Every stackable item in TLD has a default units per stack and the configured units are treated as one when being dropped or moved, so med pills and matches are moved in stacks.

**Comment by Fozzy50** [comment]
Actually, this bug is in vanilla game ; the culprit is not QoL mod...
you can check with any container ; if you have stacked items in your inventory, like sticks, for more than the remaining space in the container. Then the UI to choose quantity to transfer don't even show...
Same for any item...
________________________________
De : BA ***@***.***>
Envoyé : lundi 11 décembre 2023 19:12
À : No3371/TLD-QoL ***@***.***>
Cc : Fozzy50 ***@***.***>; Author ***@***.***>
Objet : Re: [No3371/TLD-QoL] Can't transfert even 1 item to container if total stack is too much (Issue #3)


What item is it? How much weight is left?

QoL basically only bridge input to existing TLD code, by clicking on the original arrow button it seems like that's how it has been working, not a new issue created by QoL:

Every stackable item in TLD has a default units per stack and the configured units are treated as one when being dropped or moved, so med pills and matches are moved in stacks.

**Comment by No3371** [comment]
Yes, so this won't be "fixed".

While I technically can do something about it, and it's actually a suiting addition to QoL, I'd like to keep it as is, because it'd be much more fragile (easy to be broken by updates) when it does more than just calling vanilla UI interaction.

**Comment by No3371** [comment]
It's still possible I'll do it the next time QoL getting an update. No plan for now.
