### ISSUE TITLE
Trying to harvest pre-existing corpse crashes game

### ISSUE THREAD

**Issue by AstroDisastro** [No3371/TLD-QoL#4]
I had just started a new game after downloading this mod, and I started off in Ash Canyon, and started making my way up to the gold mine. I find a wolf corpse in the cave that brings you up to said gold mine, with the waterfall inside. Interacting with it to harvest it crashes my game, and I lose my progress. I go back again, make sure my game saves before trying to harvest a deer corpse that spawned this time by the human corpse in the room with the rope. I try three or four times and all of them crash my game.

**Comment by No3371** [comment]
Please show logs so we can identify the exact issue. If you need assistance, use the !log command in the TLD Modding Discord, the bot is very useful.

**Comment by AstroDisastro** [comment]
[Latest.log](https://github.com/No3371/TLD-QoL/files/15369533/Latest.log)

**Comment by No3371** [comment]
So I guess you don't engage in the Discord server much?
You are using ML 0.6.2, which is known to be mess with TLD mods long since. ML 0.6.1 is required.
There are a lot of common problems and answers like this available in the server.

**Comment by AstroDisastro** [comment]
yeah, that would do it

**Comment by AstroDisastro** [comment]
it's working now, thanks
