### ISSUE TITLE
Drop key does not work in v2.33

### ISSUE THREAD

**Issue by stann1** [No3371/TLD-QoL#6]
The latest update seems to break some functionality - mainly when using the drop key, but I guess some other parts will also be affected. Here is the culprit, seems like a method got renamed:

`[15:00:16.108] [Il2CppInterop] During invoking native->managed trampoline
System.MissingMethodException: Method not found: 'Il2Cpp.GearItem Il2Cpp.Panel_Inventory.GetCurrentlySelectedGearItem()'.
   at QoL.InventoryPlus.Postfix(Panel_Inventory __instance)
   at DMD<Il2Cpp.Panel_Inventory::Update>(Panel_Inventory this)
   at (il2cpp -> managed) Update(IntPtr , Il2CppMethodInfo* )`

**Comment by No3371** [comment]
Thanks for the report. TLD 2.33 support is released now.
